# Data Warehouse Truven QA - Member Enrollment Yearly

Performing QA on tables in dw_staging before moving them to data_warehouse schema

## Initialization

Just loading packages that will be used and initializing connection to GP DB.

In [1]:
import pandas as pd
import sys
import psycopg2
from tqdm.notebook import tqdm
sys.path.append('H:/uth_helpers')
from db_utils import get_dsn
import keyring

In [2]:
connection_param = 'dbname=uthealth'
connection_param+= ' user=iperez9'
connection_param+= ' port=5432'
connection_param+= ' host=spgpcdplv001'
connection_param+= ' password=' + keyring.get_password('local_uthealth', 'iperez9')
connection_param+= ' keepalives=1 keepalives_idle=30 keepalives_interval=10'
connection_param+= ' application_name=dw_truv_qa_my'
connection = psycopg2.connect(connection_param)
connection.autocommit = True

## Member Counts and Member Months

This table is an aggregate of the member_enrollment_monthly table where enrollment data is aggregated to a yearly level.

Because of this, we cannot compare the row count of the raw tables with this table since enrollment tables from raw data sources are usually not on a yearly level. Instead, we can try to compare the Member Months (MM) and other columns to see if the aggregrate logic implemented is working as intended

In [3]:
query = '''drop table if exists qa_reporting.dw_truv_mbr_enrl_yearly;
create table qa_reporting.dw_truv_mbr_enrl_yearly
(
    data_source text,
    calendar_year int,
    table_src text,
    dw_row_count int,
    dw_uth_mbr_id_count int,
    dw_src_mbr_id_count int,
    src_mbr_count int,
    mbr_count_diff int,
    mbr_count_percentage float,
    dw_mm int,
    src_mm int,
    mm_diff int,
    mm_diff_percentage float,
    date_generated date
);
'''

with connection.cursor() as cursor:
    cursor.execute(query)

In [4]:
with connection.cursor() as cursor:
      query = '''
insert into qa_reporting.dw_truv_mbr_enrl_yearly
(data_source, calendar_year, table_src, dw_row_count, dw_uth_mbr_id_count, dw_src_mbr_id_count, dw_mm,date_generated)
select data_source, 
        year, 
        table_id_src, 
        count(*),
        count(distinct uth_member_id),
        count(distinct member_id_src),
        sum(total_enrolled_months),
        now()::date
  from dw_staging.truc_member_enrollment_yearly
 group by 1,2,3;
      '''

      cursor.execute(query)

      query = '''
insert into qa_reporting.dw_truv_mbr_enrl_yearly
(data_source, calendar_year, table_src, dw_row_count, dw_uth_mbr_id_count, dw_src_mbr_id_count, dw_mm,date_generated)
select data_source, 
        year, 
        table_id_src, 
        count(*),
        count(distinct uth_member_id),
        count(distinct member_id_src),
        sum(total_enrolled_months),
        now()::date
  from dw_staging.trum_member_enrollment_yearly
 group by 1,2,3;
      '''

      cursor.execute(query)

In [5]:
with connection.cursor() as cursor:
    
      query = '''
update qa_reporting.dw_truv_mbr_enrl_yearly a
set src_mbr_count = b.pat_count,
    mbr_count_diff = a.dw_src_mbr_id_count - b.pat_count,
    mbr_count_percentage = abs(a.dw_src_mbr_id_count - b.pat_count) / b.pat_count
from qa_reporting.truven_counts b
where a.calendar_year = b.year
and a.table_src = b.table_name
;
      '''

      cursor.execute(query)

      query = '''
with enrl_months as(
select 'ccaet' as table_name, year, enrolid, extract(month from dtstart) as enrolled_month
from truven.ccaet
union
select 'mdcrt' as table_name, year, enrolid, extract(month from dtstart) as enrolled_month
from truven.mdcrt
),
enrl_my as (
    select table_name, year, count(enrolled_month) as mm
    from enrl_months
    group by 1,2
)
update qa_reporting.dw_truv_mbr_enrl_yearly a
set src_mm = b.mm,
    mm_diff = a.dw_mm - b.mm,
    mm_diff_percentage = abs(a.dw_mm - b.mm) / b.mm
from enrl_my b
where a.calendar_year = b.year
and a.table_src = b.table_name
;
      '''

      cursor.execute(query)

In [6]:
df = pd.read_sql('''select * 
from qa_reporting.dw_truv_mbr_enrl_yearly 
order by mm_diff ;''', con=connection)
df

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,data_source,calendar_year,table_src,dw_row_count,dw_uth_mbr_id_count,dw_src_mbr_id_count,src_mbr_count,mbr_count_diff,mbr_count_percentage,dw_mm,src_mm,mm_diff,mm_diff_percentage,date_generated
0,truc,2018,ccaet,27087740,27087740,27087740,27087740,0,0.0,275947642,275947642,0,0.0,2024-10-24
1,truc,2022,ccaet,21356884,21356884,21356884,21356884,0,0.0,213821707,213821707,0,0.0,2024-10-24
2,truc,2014,ccaet,47258528,47258528,47258528,47258528,0,0.0,475186131,475186131,0,0.0,2024-10-24
3,truc,2019,ccaet,25388778,25388778,25388778,25388778,0,0.0,257849054,257849054,0,0.0,2024-10-24
4,truc,2011,ccaet,55559154,55559154,55559154,55559154,0,0.0,564687803,564687803,0,0.0,2024-10-24
5,truc,2020,ccaet,23306734,23306734,23306734,23306734,0,0.0,241254229,241254229,0,0.0,2024-10-24
6,truc,2017,ccaet,26146275,26146275,26146275,26146275,0,0.0,271103078,271103078,0,0.0,2024-10-24
7,truc,2013,ccaet,43737217,43737217,43737217,43737217,0,0.0,442452630,442452630,0,0.0,2024-10-24
8,truc,2016,ccaet,28717738,28717738,28717738,28717738,0,0.0,296640184,296640184,0,0.0,2024-10-24
9,truc,2021,ccaet,22828135,22828135,22828135,22828135,0,0.0,230001601,230001601,0,0.0,2024-10-24
10,truc,2012,ccaet,55975628,55975628,55975628,55975628,0,0.0,567017994,567017994,0,0.0,2024-10-24
11,truc,2015,ccaet,28348363,28348363,28348363,28348363,0,0.0,289793751,289793751,0,0.0,2024-10-24
12,trum,2013,mdcrt,4271755,4271755,4271755,4271755,0,0.0,45238676,45238676,0,0.0,2024-10-24
13,trum,2021,mdcrt,1387227,1387227,1387227,1387227,0,0.0,15439488,15439488,0,0.0,2024-10-24
14,trum,2011,mdcrt,5243029,5243029,5243029,5243029,0,0.0,56639459,56639459,0,0.0,2024-10-24
15,trum,2018,mdcrt,1130613,1130613,1130613,1130613,0,0.0,12568958,12568958,0,0.0,2024-10-24
16,trum,2017,mdcrt,1473787,1473787,1473787,1473787,0,0.0,16283781,16283781,0,0.0,2024-10-24
17,trum,2022,mdcrt,1558701,1558701,1558701,1558701,0,0.0,16975702,16975702,0,0.0,2024-10-24
18,trum,2019,mdcrt,1632440,1632440,1632440,1632440,0,0.0,18237778,18237778,0,0.0,2024-10-24
19,trum,2012,mdcrt,4874717,4874717,4874717,4874717,0,0.0,51474029,51474029,0,0.0,2024-10-24
20,trum,2014,mdcrt,3868830,3868830,3868830,3868830,0,0.0,41158746,41158746,0,0.0,2024-10-24
21,trum,2020,mdcrt,1703033,1703033,1703033,1703033,0,0.0,18995409,18995409,0,0.0,2024-10-24
22,trum,2016,mdcrt,2138719,2138719,2138719,2138719,0,0.0,23535300,23535300,0,0.0,2024-10-24
23,trum,2015,mdcrt,2199633,2199633,2199633,2199633,0,0.0,24246912,24246912,0,0.0,2024-10-24

Here we look at the overall difference of member enrollment and member count. We start of by just adding the counts for each of the source tables. However, due to how the yearly table is built, it may be better to look at member counts and member months as the data source overall.

In [7]:
df.groupby('calendar_year')[['mm_diff', 'mm_diff_percentage', 'mbr_count_diff', 'mbr_count_percentage']].sum()

,mm_diff,mm_diff_percentage,mbr_count_diff,mbr_count_percentage
calendar_year,,,,
2011,0,0.0,0,0.0
2012,0,0.0,0,0.0
2013,0,0.0,0,0.0
2014,0,0.0,0,0.0
2015,0,0.0,0,0.0
2016,0,0.0,0,0.0
2017,0,0.0,0,0.0
2018,0,0.0,0,0.0
2019,0,0.0,0,0.0
2020,0,0.0,0,0.0
2021,0,0.0,0,0.0
2022,0,0.0,0,0.0

Now we will look at the overall member count and member months rather than splitting them up based on the source table.

In [8]:
query = '''
with truv_enrl as (
    -- get unique members and their monthly enrollment to any program per calendar year
    select 'truc' as data_source, year, enrolid, extract(month from dtstart) as enrolled_month
    from truven.ccaet
    union
    select 'trum' as data_source,year, enrolid, extract(month from dtstart) as enrolled_month
    from truven.mdcrt
),
truv_enrl_counts as (
    select data_source, year, count(distinct enrolid) src_mbr_count, count(enrolled_month) src_mm
    from truv_enrl
    group by 1,2
),
dw_truv_enrl as (
    select data_source, year, count(uth_member_id) as dw_mbr_count, sum(total_enrolled_months) as dw_mm
    from dw_staging.truc_member_enrollment_yearly
    group by 1,2
    union
    select data_source, year, count(uth_member_id) as dw_mbr_count, sum(total_enrolled_months) as dw_mm
    from dw_staging.trum_member_enrollment_yearly
    group by 1,2
)
select a.data_source, a.year, a.dw_mbr_count, b.src_mbr_count, 
        a.dw_mbr_count - b.src_mbr_count as mbr_diff,
        a.dw_mm, b.src_mm, a.dw_mm - b.src_mm as mm_diff
from dw_truv_enrl a
join truv_enrl_counts b
on a.year = b.year
and a.data_source = b.data_source;'''

pd.read_sql(query, con=connection)

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,data_source,year,dw_mbr_count,src_mbr_count,mbr_diff,dw_mm,src_mm,mm_diff
0,trum,2019,1632440,1632440,0,18237778,18237778,0
1,trum,2018,1130613,1130613,0,12568958,12568958,0
2,truc,2015,28348363,28348363,0,289793751,289793751,0
3,truc,2014,47258528,47258528,0,475186131,475186131,0
4,truc,2022,21356884,21356884,0,213821707,213821707,0
5,trum,2011,5243029,5243029,0,56639459,56639459,0
6,truc,2016,28717738,28717738,0,296640184,296640184,0
7,trum,2017,1473787,1473787,0,16283781,16283781,0
8,truc,2017,26146275,26146275,0,271103078,271103078,0
9,truc,2019,25388778,25388778,0,257849054,257849054,0
10,truc,2011,55559154,55559154,0,564687803,564687803,0
11,truc,2018,27087740,27087740,0,275947642,275947642,0
12,truc,2021,22828135,22828135,0,230001601,230001601,0
13,trum,2014,3868830,3868830,0,41158746,41158746,0
14,trum,2022,1558701,1558701,0,16975702,16975702,0
15,trum,2013,4271755,4271755,0,45238676,45238676,0
16,trum,2015,2199633,2199633,0,24246912,24246912,0
17,trum,2020,1703033,1703033,0,18995409,18995409,0
18,truc,2013,43737217,43737217,0,442452630,442452630,0
19,trum,2016,2138719,2138719,0,23535300,23535300,0
20,trum,2021,1387227,1387227,0,15439488,15439488,0
21,trum,2012,4874717,4874717,0,51474029,51474029,0
22,truc,2020,23306734,23306734,0,241254229,241254229,0
23,truc,2012,55975628,55975628,0,567017994,567017994,0

## Gender Counts

Just like with the monthly enrollment table, we need to check the counts and values of the other columns. Here we take a look at the gender_cd column

In [9]:
query = '''with truven_gen_cd as (
    select 'truc' as data_source, year, enrolid, sex
    from truven.ccaet
    union
    select 'trum' as data_source, year, enrolid, sex
    from truven.mdcrt
),
truven_gen as (
    select m.data_source, year, c.gender_cd, count(*) gender_count
    from truven_gen_cd m
    left outer join reference_tables.ref_gender c
    on c.data_source = 'trv'
    and c.gender_cd_src = m.sex::text
    group by 1,2,3
), dw_gen as (
    select data_source, year, gender_cd, count(*) gender_count
    from dw_staging.trum_member_enrollment_yearly
    group by 1,2,3
    union
    select data_source, year, gender_cd, count(*) gender_count
    from dw_staging.truc_member_enrollment_yearly
    group by 1,2,3
)
select a.*, b.gender_count as src_gender_count, 
        a.gender_count - b.gender_count as gender_diff, 
        100. * abs(a.gender_count - b.gender_count) / b.gender_count as gender_diff_percent
from truven_gen b
full outer join dw_gen a
on a.year = b.year
and a.gender_cd = b.gender_cd
and a.data_source = b.data_source
order by year, gender_cd;
'''

pd.read_sql(query,  con=connection)

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,data_source,year,gender_cd,gender_count,src_gender_count,gender_diff,gender_diff_percent
0,truc,2011,F,28440593,28440593,0,0.0
1,trum,2011,F,2894340,2894340,0,0.0
2,trum,2011,M,2348689,2348689,0,0.0
3,truc,2011,M,27118561,27118561,0,0.0
4,truc,2012,F,28645853,28645853,0,0.0
5,trum,2012,F,2679931,2679931,0,0.0
6,truc,2012,M,27329775,27329775,0,0.0
7,trum,2012,M,2194786,2194786,0,0.0
8,truc,2013,F,22434271,22434271,0,0.0
9,trum,2013,F,2321532,2321532,0,0.0
10,trum,2013,M,1950223,1950223,0,0.0
11,truc,2013,M,21302946,21302946,0,0.0
12,trum,2014,F,2096879,2096879,0,0.0
13,truc,2014,F,24226585,24226585,0,0.0
14,truc,2014,M,23031943,23031943,0,0.0
15,trum,2014,M,1771951,1771951,0,0.0
16,trum,2015,F,1209895,1209895,0,0.0
17,truc,2015,F,14671838,14671838,0,0.0
18,truc,2015,M,13676525,13676525,0,0.0
19,trum,2015,M,989738,989738,0,0.0
20,truc,2016,F,14874148,14874148,0,0.0
21,trum,2016,F,1177749,1177749,0,0.0
22,trum,2016,M,960970,960970,0,0.0
23,truc,2016,M,13843590,13843590,0,0.0
24,trum,2017,F,803929,803929,0,0.0
25,truc,2017,F,13506936,13506936,0,0.0
26,trum,2017,M,669858,669858,0,0.0
27,truc,2017,M,12639339,12639339,0,0.0
28,truc,2018,F,13887183,13887183,0,0.0
29,trum,2018,F,625364,625364,0,0.0
30,truc,2018,M,13200557,13200557,0,0.0
31,trum,2018,M,505249,505249,0,0.0
32,trum,2019,F,899270,899270,0,0.0
33,truc,2019,F,13023450,13023450,0,0.0
34,truc,2019,M,12365328,12365328,0,0.0
35,trum,2019,M,733170,733170,0,0.0
36,trum,2020,F,945007,945007,0,0.0
37,truc,2020,F,11942522,11942522,0,0.0
38,truc,2020,M,11364212,11364212,0,0.0
39,trum,2020,M,758026,758026,0,0.0
40,trum,2021,F,768675,768675,0,0.0
41,truc,2021,F,11678538,11678538,0,0.0
42,truc,2021,M,11149597,11149597,0,0.0
43,trum,2021,M,618552,618552,0,0.0
44,trum,2022,F,876217,876217,0,0.0
45,truc,2022,F,10963502,10963502,0,0.0
46,trum,2022,M,682484,682484,0,0.0
47,truc,2022,M,10393382,10393382,0,0.0

## Plan Type

Check if plan types are properly mapped at a yearly level. If the plan type counts do not match between the member_enrollment_yearly table and the raw enrollment table, it most likely occurred when cleaning up the plan_type column. Ideally the count difference should be <= 0.

In [10]:
query = '''with truven_enroll as (
    select 'truc' as data_source, year, enrolid, plantyp
    from truven.ccaet
    union
    select 'trum' as data_source, year, enrolid, plantyp
    from truven.mdcrt
),
truven_plans as (
    select m.data_source, year, d.plan_type, count(*) plan_count
    from truven_enroll m
    left outer join reference_tables.ref_plan_type d
    on d.data_source = 'trv'
  and d.plan_type_src::int = m.plantyp 
    group by 1,2,3
), dw_plans as (
    select data_source, year, plan_type, count(*) plan_count
    from dw_staging.truc_member_enrollment_yearly
    group by 1,2,3
    union
    select data_source, year, plan_type, count(*) plan_count
    from dw_staging.trum_member_enrollment_yearly
    group by 1,2,3
)
select a.*, b.plan_count as src_plan_count, 
        a.plan_count - b.plan_count as plan_diff, 
        100. * abs(a.plan_count - b.plan_count) / b.plan_count as plan_diff_percent
from truven_plans b
join dw_plans a
on a.year = b.year
and a.plan_type = b.plan_type
and a.data_source = b.data_source
order by year;
'''

plan_type_counts_df = pd.read_sql(query,  con=connection)
plan_type_counts_df

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,data_source,year,plan_type,plan_count,src_plan_count,plan_diff,plan_diff_percent
0,truc,2011,CDHP,2133091,2142622,-9531,0.444829
1,trum,2011,CDHP,13703,13788,-85,0.616478
2,truc,2011,CMP,760764,797369,-36605,4.590723
3,trum,2011,HMO,603020,604629,-1609,0.266114
4,truc,2011,PPO,35153493,35322196,-168703,0.477612
...,...,...,...,...,...,...,...
168,trum,2022,HDHP,22292,22346,-54,0.241654
169,truc,2022,POS,2581991,2593315,-11324,0.436661
170,trum,2022,CDHP,5764,5811,-47,0.808811
171,trum,2022,PPO,864365,867789,-3424,0.394566
172,truc,2022,HDHP,3326950,3346184,-19234,0.574804

In [11]:
plan_type_counts_df.groupby('year')['plan_diff_percent'].min(), plan_type_counts_df.groupby('year')['plan_diff_percent'].max()

(year
 2011    0.094561
 2012    0.126337
 2013    0.226725
 2014    0.307192
 2015    0.155604
 2016    0.129447
 2017    0.100513
 2018    0.059592
 2019    0.000000
 2020    0.000000
 2021    0.188186
 2022    0.241654
 Name: plan_diff_percent, dtype: float64,
 year
 2011    4.590723
 2012    4.161845
 2013    3.114153
 2014    3.727955
 2015    3.089090
 2016    2.990624
 2017    1.918633
 2018    2.014752
 2019    2.932677
 2020    8.132530
 2021    4.150608
 2022    4.410012
 Name: plan_diff_percent, dtype: float64)

In [12]:
plan_type_counts_df.sort_values('plan_diff_percent')

,data_source,year,plan_type,plan_count,src_plan_count,plan_diff,plan_diff_percent
115,trum,2019,BMM,9,9,0,0.000000
137,trum,2020,EPO,1143,1143,0,0.000000
114,trum,2019,POS,36356,36367,-11,0.030247
130,trum,2020,POS,8597,8602,-5,0.058126
101,trum,2018,POS,46958,46986,-28,0.059592
...,...,...,...,...,...,...,...
148,truc,2021,BMM,3233,3373,-140,4.150608
23,truc,2012,EPO,1065980,1112271,-46291,4.161845
161,truc,2022,BMM,4010,4195,-185,4.410012
2,truc,2011,CMP,760764,797369,-36605,4.590723
139,truc,2020,BMM,2440,2656,-216,8.132530

In [13]:
plan_types_agg_df = plan_type_counts_df.groupby('year')['plan_count', 'src_plan_count', 'plan_diff'].sum()
plan_types_agg_df

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_22844\2142812793.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  plan_types_agg_df = plan_type_counts_df.groupby('year')['plan_count', 'src_plan_count', 'plan_diff'].sum()

      plan_count  src_plan_count  plan_diff
year
2011    56234058        56639923    -405865
2012    56365447        56719207    -353760
2013    47205689        47536034    -330345
2014    47291917        47769682    -477765
2015    29781940        30044207    -262267
2016    30361760        30649097    -287337
2017    27144179        27266303    -122124
2018    27496336        27618006    -121670
2019    26571547        26719852    -148305
2020    24453571        24628708    -175137
2021    23706237        23848467    -142230
2022    22438255        22556265    -118010

There are members that do not have a plantyp in the raw data for a given month. Let's see if the number of null plan types decrease at a yearly level

In [14]:
query = '''with truven_enroll as (
    select 'truc' as data_source, year, enrolid, plantyp
    from truven.ccaet
    where plantyp is null
    union
    select 'trum' as data_source, year, enrolid, plantyp
    from truven.mdcrt
    where plantyp is null
),
truven_plans as (
    select data_source, year, count(*) plan_count
    from truven_enroll
    group by 1,2
), dw_plans as (
    select data_source, year, count(*) plan_count
    from dw_staging.trum_member_enrollment_yearly
    where plan_type is null
    group by 1,2
    union
    select data_source, year, count(*) plan_count
    from dw_staging.truc_member_enrollment_yearly
    where plan_type is null
    group by 1,2
)
select a.*, b.plan_count as src_plan_count, 
        a.plan_count - b.plan_count as plan_diff, 
        100. * abs(a.plan_count - b.plan_count) / b.plan_count as plan_diff_percent
from truven_plans b
join dw_plans a
on a.year = b.year
and a.data_source = b.data_source
order by year;
'''

df = pd.read_sql(query,  con=connection)
df

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

   data_source  year  plan_count  src_plan_count  plan_diff  plan_diff_percent
0         truc  2011     4337455         4414774     -77319           1.751369
1         trum  2011      230670          232211      -1541           0.663621
2         trum  2012      199717          201468      -1751           0.869121
3         truc  2012     4285181         4320736     -35555           0.822892
4         truc  2013      728104          740882     -12778           1.724701
5         trum  2013       75179           75534       -355           0.469987
6         truc  2014     3787841         3826044     -38203           0.998499
7         trum  2014       47600           47911       -311           0.649120
8         trum  2015       23451           23723       -272           1.146567
9         truc  2015      742605          830666     -88061          10.601252
10        truc  2016      474373          512760     -38387           7.486348
11        trum  2016       20324           20687       -363           1.754725
12        truc  2017      435458          489199     -53741          10.985509
13        trum  2017       40425           40852       -427           1.045236
14        trum  2018       20107           20247       -140           0.691460
15        truc  2018      701910          734628     -32718           4.453683
16        trum  2019       86514           87458       -944           1.079375
17        truc  2019      363157          419846     -56689          13.502332
18        trum  2020      127496          128646      -1150           0.893926
19        truc  2020      428700          996299    -567599          56.970749
20        truc  2021      417972          438016     -20044           4.576089
21        trum  2021       91153           92521      -1368           1.478583
22        truc  2022      379463          403084     -23621           5.860069
23        trum  2022       97867          102539      -4672           4.556315

## BUS_CD

In [15]:
query = '''with truven_enroll as (
    select 'truc' as data_source,  year, enrolid, case when medadv = '1' then 'MA' else 'COM' end as bus_cd
    from truven.ccaet
    union
    select 'trum' as data_source, year, enrolid, case when medadv = '1' then 'MA' else 'MS' end as bus_cd
    from truven.mdcrt
),
truven_plans as (
    select data_source, year, bus_cd, count(*) plan_count
    from truven_enroll
    group by 1,2,3
), dw_plans as (
    select data_source, year, bus_cd, count(*) plan_count
    from dw_staging.truc_member_enrollment_yearly
    group by 1,2,3
    union
    select data_source, year, bus_cd, count(*) plan_count
    from dw_staging.trum_member_enrollment_yearly
    group by 1,2,3
)
select a.*, b.plan_count as src_plan_count, 
        a.plan_count - b.plan_count as plan_diff, 
        100. * abs(a.plan_count - b.plan_count) / b.plan_count as plan_diff_percent
from truven_plans b
full join dw_plans a
on a.year = b.year
and a.bus_cd = b.bus_cd
and a.data_source = b.data_source
order by year;
'''

df = pd.read_sql(query,  con=connection)
df

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,data_source,year,bus_cd,plan_count,src_plan_count,plan_diff,plan_diff_percent
0,truc,2011,COM,55559154,55559154,0,0.000000
1,trum,2011,MS,5243029,5243029,0,0.000000
2,trum,2012,MS,4874717,4874717,0,0.000000
3,truc,2012,COM,55975628,55975628,0,0.000000
4,truc,2013,COM,43737217,43737217,0,0.000000
5,trum,2013,MS,4271755,4271755,0,0.000000
6,trum,2014,MS,3868830,3868830,0,0.000000
7,truc,2014,COM,47258528,47258528,0,0.000000
8,trum,2015,MS,2199633,2199633,0,0.000000
9,truc,2015,COM,28348363,28348363,0,0.000000
10,trum,2016,MS,2138719,2138719,0,0.000000
11,truc,2016,COM,28717738,28717738,0,0.000000
12,truc,2017,COM,26146275,26146275,0,0.000000
13,trum,2017,MS,1473787,1473787,0,0.000000
14,trum,2018,MS,1130613,1130613,0,0.000000
15,truc,2018,COM,27087740,27087740,0,0.000000
16,trum,2019,MS,1122716,1125781,-3065,0.272255
17,truc,2019,COM,25388778,25388778,0,0.000000
18,trum,2019,MA,509724,512140,-2416,0.471746
19,trum,2020,MA,718416,720990,-2574,0.357009
20,truc,2020,COM,23306734,23306734,0,0.000000
21,trum,2020,MS,984617,988787,-4170,0.421729
22,trum,2021,MS,624754,629076,-4322,0.687039
23,trum,2021,MA,762473,765671,-3198,0.417673
24,truc,2021,COM,22828135,22828135,0,0.000000
25,trum,2022,MA,1039795,1043212,-3417,0.327546
26,truc,2022,COM,21356884,21356884,0,0.000000
27,trum,2022,MS,518906,523514,-4608,0.880206

In [16]:
df = df.groupby('year')['plan_count', 'src_plan_count', 'plan_diff'].sum()
df['percent_diff'] = 100. * abs(df['plan_count'] - df['src_plan_count']) / df['src_plan_count']
df

C:\Users\iperez9\AppData\Local\Temp\3\ipykernel_22844\4118100362.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df = df.groupby('year')['plan_count', 'src_plan_count', 'plan_diff'].sum()

      plan_count  src_plan_count  plan_diff  percent_diff
year
2011    60802183        60802183          0      0.000000
2012    60850345        60850345          0      0.000000
2013    48008972        48008972          0      0.000000
2014    51127358        51127358          0      0.000000
2015    30547996        30547996          0      0.000000
2016    30856457        30856457          0      0.000000
2017    27620062        27620062          0      0.000000
2018    28218353        28218353          0      0.000000
2019    27021218        27026699      -5481      0.020280
2020    25009767        25016511      -6744      0.026958
2021    24215362        24222882      -7520      0.031045
2022    22915585        22923610      -8025      0.035008

## State

In [17]:
query = '''with truven_enroll as (
    select 'truc' as data_source, year, enrolid, egeoloc
    from truven.ccaet
    union
    select 'trum' as data_source, year, enrolid, egeoloc
    from truven.mdcrt
),
truven_plans as (
    select data_source, year::int, case when length(s.abbr) > 2 then '' when m.egeoloc is null then 'null' else s.abbr  end as state, count(*) state_count
    from truven_enroll m
    left outer join reference_tables.ref_truven_state_codes s 
    on m.egeoloc=s.truven_code
    group by 1,2,3
), dw_plans as (
    select data_source, year, case when state is null then 'null' else state end as state, count(*) state_count
    from dw_staging.truc_member_enrollment_yearly
    group by 1,2,3
    union
    select data_source, year, case when state is null then 'null' else state end as state, count(*) state_count
    from dw_staging.trum_member_enrollment_yearly
    group by 1,2,3
)
select a.*, b.state_count as src_state_count, 
        a.state_count - b.state_count as plan_diff, 
        100. * abs(a.state_count - b.state_count) / b.state_count as plan_diff_percent
from truven_plans b
full join dw_plans a
on a.year = b.year
and a.state = b.state
and a.data_source = b.data_source
order by year;
'''

df = pd.read_sql(query,  con=connection)
df

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,data_source,year,state,state_count,src_state_count,plan_diff,plan_diff_percent
0,trum,2011,MT,25053,25238,-185,0.733022
1,truc,2011,CT,943888,969464,-25576,2.638159
2,trum,2011,OK,99198,99370,-172,0.173090
3,trum,2011,DE,29160,29377,-217,0.738673
4,trum,2011,NJ,98938,99638,-700,0.702543
...,...,...,...,...,...,...,...
1267,truc,2022,OR,333793,338547,-4754,1.404236
1268,trum,2022,MN,4577,4645,-68,1.463940
1269,trum,2022,NH,3983,4050,-67,1.654321
1270,truc,2022,DE,89446,91117,-1671,1.833906
1271,truc,2022,ME,60285,61301,-1016,1.657395

We see that there is a large difference in state values assigned using DW logic compared to raw data. Ideally the difference should show that there are more values in the raw data compared to the values in DW due, especially for state values of NULL and ''. When this happens, it means that the member now has a valid state value which can be used to group these member in future projects.

In [18]:
df.sort_values('plan_diff_percent', ascending=False)

,data_source,year,state,state_count,src_state_count,plan_diff,plan_diff_percent
397,truc,2014,,1112700,1541140,-428440,27.800200
1033,truc,2020,PR,665,877,-212,24.173318
746,truc,2018,PR,848,1088,-240,22.058824
211,truc,2012,,1192425,1525493,-333068,21.833466
245,truc,2013,,1197652,1531795,-334143,21.813820
...,...,...,...,...,...,...,...
359,trum,2014,LA,133239,133422,-183,0.137159
213,trum,2013,LA,133839,134009,-170,0.126857
527,trum,2015,LA,109369,109464,-95,0.086787
541,trum,2016,LA,110923,111000,-77,0.069369
1060,trum,2021,ID,6,6,0,0.000000

In [19]:
df['state'].unique()

array(['MT', 'CT', 'OK', 'DE', 'NJ', 'IL', 'KY', 'MA', 'WA', 'AR', 'PR',
       'MS', 'CO', 'PA', 'NY', 'IA', 'LA', 'MN', 'NE', 'OR', 'TN', 'AZ',
       'ID', 'ME', 'OH', 'TX', 'SC', 'NM', '', 'CA', 'NV', 'NH', 'WI',
       'DC', 'GA', 'WV', 'HI', 'KS', 'VA', 'SD', 'NC', 'VT', 'MO', 'WY',
       'ND', 'AL', 'RI', 'FL', 'MI', 'IN', 'UT', 'MD', 'AK', 'null'],
      dtype=object)

In [20]:
df[df['state'] == '']

,data_source,year,state,state_count,src_state_count,plan_diff,plan_diff_percent
36,trum,2011,,121195,133778,-12583,9.405881
99,truc,2011,,1661011,1783095,-122084,6.846747
184,trum,2012,,141729,161825,-20096,12.418353
211,truc,2012,,1192425,1525493,-333068,21.833466
245,truc,2013,,1197652,1531795,-334143,21.813820
248,trum,2013,,80231,99161,-18930,19.090166
397,truc,2014,,1112700,1541140,-428440,27.800200
402,trum,2014,,82177,98319,-16142,16.417986
454,trum,2015,,2634,3079,-445,14.452744
472,truc,2015,,85822,103218,-17396,16.853650
560,truc,2016,,92935,113377,-20442,18.030112
608,trum,2016,,3045,3349,-304,9.077337
654,trum,2017,,574210,578399,-4189,0.724241
655,truc,2017,,3457677,3510316,-52639,1.499552
754,truc,2018,,2398373,2423857,-25484,1.051382
842,trum,2018,,562192,565393,-3201,0.566155
891,trum,2019,,787043,791818,-4775,0.603043
951,truc,2019,,2446951,2473624,-26673,1.078296
996,trum,2020,,794574,798704,-4130,0.517088
1018,truc,2020,,2209563,2234157,-24594,1.100818
1124,trum,2021,,451795,453744,-1949,0.429537
1150,truc,2021,,3365194,3399577,-34383,1.011391
1200,truc,2022,,3350715,3386319,-35604,1.051407
1243,trum,2022,,454395,457122,-2727,0.596558

In [21]:
query = '''with truven_enroll as (
    select 'truc' as data_source, year, enrolid, egeoloc
    from truven.ccaet
    union
    select 'trum' as data_source, year, enrolid, egeoloc
    from truven.mdcrt
)
    select data_source, year, case when length(s.abbr) > 2 then '' else s.abbr end as state, count(*) state_count
    from truven_enroll m
    left outer join reference_tables.ref_truven_state_codes s 
    on m.egeoloc=s.truven_code
    group by 1,2,3'''

temp = pd.read_sql(query,  con=connection)

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [22]:
temp

     data_source    year state  state_count
0           truc  2013.0    DC        26070
1           truc  2016.0    PA       848384
2           truc  2018.0            2423857
3           truc  2018.0    NY      2223720
4           trum  2018.0    AL         4097
...          ...     ...   ...          ...
1267        trum  2017.0    SC        11465
1268        trum  2017.0    UT         1523
1269        trum  2017.0    WV         1604
1270        trum  2019.0    TN        14476
1271        trum  2021.0    MT          446

[1272 rows x 4 columns]

In [23]:
temp[temp['state'].isin([None])]

     data_source    year state  state_count
181         truc  2021.0  None        10865
406         trum  2022.0  None          193
755         trum  2021.0  None          201
1256        truc  2022.0  None        11882