# Data Warehouse Truven QA - Claim Diag

## Initialization

Just loading packages that will be used and initializing connection to GP DB.

In [1]:
import pandas as pd
import sys
import psycopg2
from tqdm import tqdm
sys.path.append('H:/uth_helpers')
from db_utils import get_dsn
import keyring

In [2]:
connection_param = 'dbname=uthealth'
connection_param+= ' user=iperez9'
connection_param+= ' port=5432'
connection_param+= ' host=spgpcdplv001'
connection_param+= ' password=' + keyring.get_password('local_uthealth', 'iperez9')
connection_param+= ' keepalives=1 keepalives_idle=30 keepalives_interval=10'
connection_param+= ' application_name=dw_truv_qa_mm'
connection = psycopg2.connect(connection_param)
connection.autocommit = True

## Row Count and Claim Count

Similar to the member_enrollment_monthly table, the claim_header table has the row count should equal the number of unique claims.

For this table, we extract claim data from the s, o, and f tables from the truven schema.

In [17]:
query = ''' drop table if exists qa_reporting.dw_truv_claim_diag_counts;
create table qa_reporting.dw_truv_claim_diag_counts
(
    data_source bpchar(4),
    table_id_src text,
    calendar_year int,
    dw_row_count bigint,
    src_row_count bigint,
    row_count_diff bigint,
    row_count_percentage float,
    dw_uth_clm_id_count bigint,
    dw_src_clm_id_count bigint,
    src_clm_count bigint,
    clm_count_diff bigint,
    clm_count_percentage float,
    dw_uth_mbr_id_count bigint,
    dw_src_mbr_id_count bigint,
    src_mbr_count bigint,
    mbr_count_diff bigint,
    mbr_count_percentage float,
    date_generated date
);
'''

with connection.cursor() as cursor:
    cursor.execute(query)

In [6]:
year_df = pd.read_sql('select distinct year from dw_staging.trum_claim_diag;', con=connection)

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [18]:
with connection.cursor() as cursor:
    for year in tqdm(year_df['year']):
        query = f'''
        insert into qa_reporting.dw_truv_claim_diag_counts
        (data_source, calendar_year, table_id_src, dw_row_count, date_generated)
        select data_source, year, table_id_src, count(*), current_date
        from dw_staging.trum_claim_diag
        where year = {year}
        group by 1, 2, 3
        '''
        
        cursor.execute(query)

        query = f'''
        update qa_reporting.dw_truv_claim_diag_counts b
        set dw_uth_clm_id_count = count
        from (
            select data_source, year, table_id_src, count(distinct uth_claim_id) as count 
            from dw_staging.trum_claim_diag
        where year = {year}
        group by 1, 2, 3) a
        where a.year = b.calendar_year
        and a.table_id_src = b.table_id_src
        '''

        cursor.execute(query)

        query = f'''
        update qa_reporting.dw_truv_claim_diag_counts b
        set dw_src_clm_id_count = count
        from (
            select data_source, year, table_id_src, count(distinct claim_id_src) as count 
            from dw_staging.trum_claim_diag
        where year = {year}
        group by 1, 2, 3) a
        where a.year = b.calendar_year
        and a.table_id_src = b.table_id_src
        '''

        cursor.execute(query)

        query = f'''
        update qa_reporting.dw_truv_claim_diag_counts b
        set dw_uth_mbr_id_count = count
        from (
            select data_source, year, table_id_src, count(distinct uth_member_id) as count 
            from dw_staging.trum_claim_diag
        where year = {year}
        group by 1, 2, 3) a
        where a.year = b.calendar_year
        and a.table_id_src = b.table_id_src
        '''

        cursor.execute(query)
        
        query = f'''
        update qa_reporting.dw_truv_claim_diag_counts b
        set dw_src_mbr_id_count = count
        from (
            select data_source, year, table_id_src, count(distinct member_id_src) as count 
            from dw_staging.trum_claim_diag
        where year = {year}
        group by 1, 2, 3) a
        where a.year = b.calendar_year
        and a.table_id_src = b.table_id_src
        '''

        cursor.execute(query)

100%|██████████| 12/12 [11:47<00:00, 58.98s/it]

In [19]:
with connection.cursor() as cursor:
    for year in tqdm(year_df['year']):
        query = f'''
        insert into qa_reporting.dw_truv_claim_diag_counts
        (data_source, calendar_year, table_id_src, dw_row_count, date_generated)
        select data_source, year, table_id_src, count(*), current_date
        from dw_staging.truc_claim_diag
        where year = {year}
        group by 1, 2, 3
        '''
        
        cursor.execute(query)

        query = f'''
        update qa_reporting.dw_truv_claim_diag_counts b
        set dw_uth_clm_id_count = count
        from (
            select data_source, year, table_id_src, count(distinct uth_claim_id) as count 
            from dw_staging.truc_claim_diag
        where year = {year}
        group by 1, 2, 3) a
        where a.year = b.calendar_year
        and a.table_id_src = b.table_id_src
        '''

        cursor.execute(query)

        query = f'''
        update qa_reporting.dw_truv_claim_diag_counts b
        set dw_src_clm_id_count = count
        from (
            select data_source, year, table_id_src, count(distinct claim_id_src) as count 
            from dw_staging.truc_claim_diag
        where year = {year}
        group by 1, 2, 3) a
        where a.year = b.calendar_year
        and a.table_id_src = b.table_id_src
        '''

        cursor.execute(query)

        query = f'''
        update qa_reporting.dw_truv_claim_diag_counts b
        set dw_uth_mbr_id_count = count
        from (
            select data_source, year, table_id_src, count(distinct uth_member_id) as count 
            from dw_staging.truc_claim_diag
        where year = {year}
        group by 1, 2, 3) a
        where a.year = b.calendar_year
        and a.table_id_src = b.table_id_src
        '''

        cursor.execute(query)
        
        query = f'''
        update qa_reporting.dw_truv_claim_diag_counts b
        set dw_src_mbr_id_count = count
        from (
            select data_source, year, table_id_src, count(distinct member_id_src) as count 
            from dw_staging.truc_claim_diag
        where year = {year}
        group by 1, 2, 3) a
        where a.year = b.calendar_year
        and a.table_id_src = b.table_id_src
        '''

        cursor.execute(query)

100%|██████████| 12/12 [52:17<00:00, 261.42s/it]

In [20]:
with connection.cursor() as cursor:
    query = '''update qa_reporting.dw_truv_claim_diag_counts a
    set src_row_count = b.row_count,
    row_count_diff = dw_row_count - b.row_count,
    row_count_percentage = 100. * abs( dw_row_count - b.row_count) / b.row_count,
    src_clm_count = clm_count,
    clm_count_diff = dw_uth_clm_id_count - b.clm_count,
    clm_count_percentage = 100. * abs(dw_uth_clm_id_count - b.clm_count) / b.clm_count,
    src_mbr_count = b.pat_count,
    mbr_count_diff = dw_uth_mbr_id_count - b.pat_count,
    mbr_count_percentage = 100. * abs(dw_uth_mbr_id_count - b.pat_count) / b.pat_count
    from qa_reporting.truven_counts b
    where a.calendar_year = b.year
    and a.table_id_src = b.table_name
    ;
    '''

    cursor.execute(query)

In [13]:
with connection.cursor() as cursor:
    query = '''
with truven_claims as (
        select 'ccaes' as table_source, year, enrolid, claim_id_derv
        from truven.ccaes
        where pdx is not null or dx1 is not null
        union 
        select 'mdcrs', year, enrolid, claim_id_derv
        from truven.mdcrs
        where pdx is not null or dx1 is not null
        union
        select 'ccaeo', year, enrolid, claim_id_derv
        from truven.ccaeo
        where dx1 is not null
        union
        select 'mdcro', year, enrolid, claim_id_derv
        from truven.mdcro
        where dx1 is not null
    ),
truven_claims_counts as (
        select table_source, year as calendar_year, count(*) as src_row_count, count(distinct enrolid) src_mbr_count, count(distinct claim_id_derv) src_clm_count
        from truven_claims
        group by 1,2
    )
update qa_reporting.dw_truv_claim_diag_counts a
set src_row_count = b.src_row_count,
row_count_diff = a.dw_row_count - b.src_row_count,
row_count_percentage = 100. * abs(a.dw_row_count - b.src_row_count) / b.src_row_count,
src_clm_count = b.src_clm_count,
clm_count_diff = a.dw_uth_clm_id_count - b.src_clm_count,
clm_count_percentage = 100. * abs(a.dw_uth_clm_id_count - b.src_clm_count) / b.src_clm_count,
src_mbr_count = b.src_mbr_count,
mbr_count_diff = a.dw_uth_mbr_id_count - b.src_mbr_count,   
mbr_count_percentage = 100. * abs(a.dw_uth_mbr_id_count - b.src_mbr_count) / b.src_mbr_count
from truven_claims_counts b
where a.calendar_year = b.calendar_year
and a.table_id_src = b.table_source
;
    '''

    cursor.execute(query)

KeyboardInterrupt:

In [21]:
query = '''select * from qa_reporting.dw_truv_claim_diag_counts;'''

df = pd.read_sql(query, con=connection)

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

Row counts may be very different due to how the data is transformed to match the Data Warehouse format.

In [22]:
df[df['data_source'] == 'trum'].sort_values(['table_id_src', 'calendar_year'])

,data_source,table_id_src,calendar_year,dw_row_count,src_row_count,row_count_diff,row_count_percentage,dw_uth_clm_id_count,dw_src_clm_id_count,src_clm_count,clm_count_diff,clm_count_percentage,dw_uth_mbr_id_count,dw_src_mbr_id_count,src_mbr_count,mbr_count_diff,mbr_count_percentage,date_generated
46,trum,mdcro,2011,176625388,234255047,-57629659,24.601245,106356165,106353876,106577308,-221143,0.207495,4743002,4743002,4750926,-7924,0.166789,2024-10-25
32,trum,mdcro,2012,176369136,229768218,-53399082,23.240413,99191081,99189188,99450749,-259668,0.261102,4383978,4383978,4391031,-7053,0.160623,2024-10-25
26,trum,mdcro,2013,166902519,208095580,-41193061,19.795260,87924600,87922903,88058549,-133949,0.152114,3805615,3805615,3812531,-6916,0.181402,2024-10-25
33,trum,mdcro,2014,165212697,193877526,-28664829,14.785019,79392969,79390350,79544615,-151646,0.190643,3505316,3505316,3514364,-9048,0.257458,2024-10-25
47,trum,mdcro,2015,107866703,121473554,-13606851,11.201492,49654224,49652846,49736837,-82613,0.166100,2032094,2032094,2034639,-2545,0.125084,2024-10-25
27,trum,mdcro,2016,112189858,118982284,-6792426,5.708771,48777662,48775710,48879522,-101860,0.208390,1969257,1969257,1972505,-3248,0.164664,2024-10-25
37,trum,mdcro,2017,79755426,81837912,-2082486,2.544647,34022221,34020344,34120595,-98374,0.288313,1362310,1362310,1364765,-2455,0.179884,2024-10-25
39,trum,mdcro,2018,61390573,59193949,2196624,3.710893,26046141,26044371,26105522,-59381,0.227465,1056142,1056142,1057428,-1286,0.121616,2024-10-25
29,trum,mdcro,2019,100283998,99576131,707867,0.710880,42174136,42173028,42280035,-105899,0.250470,1541958,1541958,1543372,-1414,0.091618,2024-10-25
44,trum,mdcro,2020,94251032,94012150,238882,0.254097,39723440,39722867,39967420,-243980,0.610447,1595444,1595444,1597557,-2113,0.132264,2024-10-25
41,trum,mdcro,2021,81731876,85945827,-4213951,4.903032,34508562,34508200,34798063,-289501,0.831946,1300533,1300533,1302878,-2345,0.179986,2024-10-25
31,trum,mdcro,2022,92750805,100717164,-7966359,7.909634,38907900,38907770,39371664,-463764,1.177913,1456323,1456323,1461117,-4794,0.328105,2024-10-25
35,trum,mdcrs,2011,30949894,32535953,-1586059,4.874789,10833340,10831871,10836750,-3410,0.031467,794165,794165,794571,-406,0.051097,2024-10-25
43,trum,mdcrs,2012,30133122,32200251,-2067129,6.419605,10013701,10011678,10014407,-706,0.007050,714015,714015,714226,-211,0.029542,2024-10-25
24,trum,mdcrs,2013,27586529,29045752,-1459223,5.023878,8710365,8708498,8711803,-1438,0.016506,599533,599533,599773,-240,0.040015,2024-10-25
34,trum,mdcrs,2014,26715735,26044601,671134,2.576864,7963900,7961283,7964806,-906,0.011375,531311,531311,531556,-245,0.046091,2024-10-25
38,trum,mdcrs,2015,17902577,16705568,1197009,7.165330,5185220,5183306,5184315,905,0.017457,336220,336220,336283,-63,0.018734,2024-10-25
36,trum,mdcrs,2016,17234800,15427500,1807300,11.714795,4812760,4811164,4812832,-72,0.001496,320511,320511,320627,-116,0.036179,2024-10-25
42,trum,mdcrs,2017,12472924,10551924,1921000,18.205211,3447624,3445562,3447394,230,0.006672,226579,226579,226681,-102,0.044997,2024-10-25
28,trum,mdcrs,2018,8416719,6992226,1424493,20.372525,2343378,2341744,2342184,1194,0.050978,147655,147655,147674,-19,0.012866,2024-10-25
25,trum,mdcrs,2019,16097895,12614703,3483192,27.612160,4434671,4433328,4434378,293,0.006607,236809,236809,236840,-31,0.013089,2024-10-25
40,trum,mdcrs,2020,15770238,12236602,3533636,28.877592,4322749,4322223,4322963,-214,0.004950,213520,213520,213552,-32,0.014985,2024-10-25
30,trum,mdcrs,2021,13420824,10194492,3226332,31.647796,3646570,3646034,3646460,110,0.003017,170638,170638,170659,-21,0.012305,2024-10-25
45,trum,mdcrs,2022,13872944,10888900,2984044,27.404458,3770778,3770706,3771793,-1015,0.026910,177737,177737,177777,-40,0.022500,2024-10-25

In [23]:
df[df['data_source'] == 'truc'].sort_values(['table_id_src', 'calendar_year'])

,data_source,table_id_src,calendar_year,dw_row_count,src_row_count,row_count_diff,row_count_percentage,dw_uth_clm_id_count,dw_src_clm_id_count,src_clm_count,clm_count_diff,clm_count_percentage,dw_uth_mbr_id_count,dw_src_mbr_id_count,src_mbr_count,mbr_count_diff,mbr_count_percentage,date_generated
5,truc,ccaeo,2011,727811837,1077661934,-349850097,32.463808,464818779,464815368,465722367,-903588,0.194019,42474852,42474852,42511345,-36493,0.085843,2024-10-25
3,truc,ccaeo,2012,770564067,1121961205,-351397138,31.319901,474750523,474746519,475937265,-1186742,0.249348,43260503,43260503,43288123,-27620,0.063805,2024-10-25
22,truc,ccaeo,2013,613008394,875696525,-262688131,29.997622,373510731,373506774,374452293,-941562,0.251450,33633095,33633095,33659811,-26716,0.079371,2024-10-25
13,truc,ccaeo,2014,726010272,952082337,-226072065,23.745012,398826552,398822102,399893229,-1066677,0.266740,36263937,36263937,36298645,-34708,0.095618,2024-10-25
15,truc,ccaeo,2015,479956520,599918568,-119962048,19.996389,253817027,253814030,254905571,-1088544,0.427038,22276330,22276330,22319003,-42673,0.191196,2024-10-25
23,truc,ccaeo,2016,519586393,623641018,-104054625,16.685019,262825845,262821831,264225295,-1399450,0.529643,22790094,22790094,22831148,-41054,0.179816,2024-10-25
10,truc,ccaeo,2017,493529127,573221660,-79692533,13.902568,243813648,243808815,245443871,-1630223,0.664194,20906587,20906587,20936299,-29712,0.141916,2024-10-25
4,truc,ccaeo,2018,514580633,589022269,-74441636,12.638170,250032366,250028329,251365523,-1333157,0.530366,21516356,21516356,21529034,-12678,0.058888,2024-10-25
18,truc,ccaeo,2019,500201418,566058850,-65857432,11.634379,241377183,241373783,242648619,-1271436,0.523982,20268922,20268922,20280269,-11347,0.055951,2024-10-25
8,truc,ccaeo,2020,445616027,485549961,-39933934,8.224475,216455753,216451366,217834256,-1378503,0.632822,18676658,18676658,18687285,-10627,0.056868,2024-10-25
1,truc,ccaeo,2021,484696782,534657936,-49961154,9.344508,239112866,239109140,240648796,-1535930,0.638245,18768666,18768666,18778579,-9913,0.052789,2024-10-25
9,truc,ccaeo,2022,449068799,491363378,-42294579,8.607597,216647765,216647259,218190608,-1542843,0.707108,17134666,17134666,17156303,-21637,0.126117,2024-10-25
11,truc,ccaes,2011,65090024,81640170,-16550146,20.272062,22335068,22331969,22342714,-7646,0.034221,2347838,2347838,2348969,-1131,0.048149,2024-10-25
12,truc,ccaes,2012,65588289,82224989,-16636700,20.233143,21968667,21964497,21970624,-1957,0.008907,2288837,2288837,2289517,-680,0.029701,2024-10-25
2,truc,ccaes,2013,50570292,62632638,-12062346,19.258882,16809477,16805405,16811236,-1759,0.010463,1720157,1720157,1720897,-740,0.043001,2024-10-25
21,truc,ccaes,2014,57916346,67268872,-9352526,13.903200,17908858,17904525,17913281,-4423,0.024691,1789658,1789658,1790870,-1212,0.067677,2024-10-25
17,truc,ccaes,2015,38078666,43216824,-5138158,11.889254,11498321,11495147,11502326,-4005,0.034819,1126339,1126339,1127160,-821,0.072838,2024-10-25
20,truc,ccaes,2016,39888194,43519648,-3631454,8.344401,11589769,11586197,11598289,-8520,0.073459,1139000,1139000,1140472,-1472,0.129069,2024-10-25
14,truc,ccaes,2017,36819385,38179525,-1360140,3.562485,10569745,10565351,10577394,-7649,0.072315,1021079,1021079,1022356,-1277,0.124908,2024-10-25
19,truc,ccaes,2018,38731733,38984126,-252393,0.647425,10975954,10971476,10976708,-754,0.006869,1028842,1028842,1029737,-895,0.086915,2024-10-25
6,truc,ccaes,2019,36689477,37047879,-358402,0.967402,10313661,10309547,10313175,486,0.004712,941769,941769,942328,-559,0.059321,2024-10-25
7,truc,ccaes,2020,34696997,33760060,936937,2.775282,9529962,9525857,9529232,730,0.007661,824930,824930,825450,-520,0.062996,2024-10-25
0,truc,ccaes,2021,35692473,33461744,2230729,6.666505,9696966,9693581,9698022,-1056,0.010889,811219,811219,811797,-578,0.071200,2024-10-25
16,truc,ccaes,2022,29698259,27302261,2395998,8.775823,8128350,8127535,8151327,-22977,0.281880,705940,705940,710429,-4489,0.631872,2024-10-25

## Diagnosis Codes

Here we will check if we have valid ICD Diagnosis codes using our reference tables.

In [24]:
query = '''drop table if exists qa_reporting.dw_truv_diag_counts;
select data_source, year, diag_cd, count(*) as diag_count
into qa_reporting.dw_truv_diag_counts
from dw_staging.trum_claim_diag
group by 1,2,3;

insert into qa_reporting.dw_truv_diag_counts
select data_source, year, diag_cd, count(*) as diag_count
from dw_staging.truc_claim_diag
group by 1,2,3;
'''

with connection.cursor() as cursor:
    cursor.execute(query)

In [25]:
diag_cd_df = pd.read_sql('select * from qa_reporting.dw_truv_diag_counts;', con=connection)
diag_cd_df

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

       data_source  year  diag_cd  diag_count
0             trum  2020  T84098S           2
1             trum  2021  S52552S           2
2             trum  2021  S72041P           1
3             trum  2020     D598         364
4             trum  2021  S60421A          13
...            ...   ...      ...         ...
940172        truc  2015     0879        2888
940173        truc  2019  V231XXA          13
940174        truc  2018   M02079           7
940175        truc  2017  S63262S           3
940176        truc  2021     I469       60155

[940177 rows x 4 columns]

We see that we have a lot of claims with diagnosis codes that are not in our reference list. If we take a further look at some of these codes, we see that in our reference list, there is at least one more digit missing from these codes. The missing digits helps specify the diagnosis code.

In [26]:
query = '''
select a.*
from qa_reporting.dw_truv_diag_counts a
left join reference_tables.ref_cms_icd_cm_codes b
on a.diag_cd = cd_value
where b.cd_value is null;
'''

invalid_diag_df = pd.read_sql(query, con=connection)
invalid_diag_df

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

     data_source  year diag_cd  diag_count
0           truc  2020  O3121X           1
1           truc  2018  W2181X           6
2           truc  2020  S2000X           1
3           truc  2017  T2612X           3
4           truc  2022  O364XX          28
...          ...   ...     ...         ...
8562        truc  2021  S0291X           7
8563        truc  2020  S5422X          16
8564        truc  2022  W2105X          13
8565        truc  2022   S272X          17
8566        trum  2017   S329X          57

[8567 rows x 4 columns]

Overall, the number of invalid diagnosis codes is neglible compared to the overall number of diagnosis codes in the claim_diag table.

In [27]:
invalid_diag_df.groupby('year')['diag_count'].sum()

year
2014        20
2016        17
2017     75082
2018     68613
2019     83543
2020     52662
2021     65171
2022    534844
Name: diag_count, dtype: int64

In [28]:
diag_comp_df = pd.DataFrame({'overall_diag_count': diag_cd_df.groupby('year')['diag_count'].sum(),
                            'invalid_diag_count': invalid_diag_df.groupby('year')['diag_count'].sum(),
                            'valid_diag_count': diag_cd_df.groupby('year')['diag_count'].sum() - invalid_diag_df.groupby('year')['diag_count'].sum()})
diag_comp_df.loc[diag_comp_df['valid_diag_count'].isna(),'valid_diag_count'] = diag_comp_df.loc[diag_comp_df['valid_diag_count'].isna(),'overall_diag_count']
diag_comp_df['valid_diag_count'] =  diag_comp_df['valid_diag_count'].astype(int)
diag_comp_df['invalid_to_valid_percent'] = 100. * diag_comp_df['invalid_diag_count'] / diag_comp_df['valid_diag_count']
diag_comp_df

,overall_diag_count,invalid_diag_count,valid_diag_count,invalid_to_valid_percent
year,,,,
2011,1000477143,NaN,1000477143,NaN
2012,1042654614,NaN,1042654614,NaN
2013,858067734,NaN,858067734,NaN
2014,975855050,20.0,975855030,0.000002
2015,643804466,NaN,643804466,NaN
2016,688899245,17.0,688899228,0.000002
2017,622576862,75082.0,622501780,0.012061
2018,623119658,68613.0,623051045,0.011012
2019,653272788,83543.0,653189245,0.012790
2020,590334294,52662.0,590281632,0.008922
2021,615541955,65171.0,615476784,0.010589
2022,585390807,534844.0,584855963,0.091449

In [29]:
invalid_diag_df.groupby('year').max()

     data_source diag_cd  diag_count
year
2014        truc    7070           6
2016        trum   X500X           3
2017        trum  Z28310        6593
2018        trum   Y33XX        4258
2019        trum  Y33XXX        4397
2020        trum  Z28311        3413
2021        trum   Y32XX        4004
2022        trum   Z91A9       54588

## Diagnosis Code Position

In [30]:
query = '''drop table if exists qa_reporting.dw_truv_diag_position;
select data_source, year, table_id_src, diag_position, count(distinct uth_claim_id) as claim_count
into qa_reporting.dw_truv_diag_position
from dw_staging.trum_claim_diag
group by 1,2,3,4;

insert into qa_reporting.dw_truv_diag_position
select data_source, year, table_id_src, diag_position, count(distinct uth_claim_id) as claim_count
from dw_staging.truc_claim_diag
group by 1,2,3,4;
'''
with connection.cursor() as cursor:
    cursor.execute(query)

In [31]:
diag_position_df = pd.read_sql('select * from qa_reporting.dw_truv_diag_position;', con=connection)
diag_position_df.sort_values(['year', 'diag_position'])

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

    data_source  year table_id_src diag_position  claim_count
2          trum  2011        mdcrs             1     10829887
89         trum  2011        mdcro             1    106352416
96         truc  2011        ccaes             1     22319363
197        truc  2011        ccaeo             1    464767402
65         trum  2011        mdcrs             2      4413927
..          ...   ...          ...           ...          ...
29         trum  2022        mdcro             4     11425636
67         trum  2022        mdcrs             4      1539385
99         truc  2022        ccaes             4      3273070
90         truc  2022        ccaes             P      8128338
202        trum  2022        mdcrs             P      3770778

[216 rows x 5 columns]

In [32]:
diag_position_df['diag_position'].unique()

array(['1', '2', '3', '4', 'P'], dtype=object)

Checking if the counts for the diag_position are correct. The higher the diag_position is, the less counts there should be. If we sort the counts of the diag_position by year and assign their order, this value should match with the diag_position value.

In [33]:
diag_position_df['row_rank'] = diag_position_df.sort_values(['data_source', 'year', 'claim_count'], ascending=[True, True, False]).groupby(['data_source', 'year', 'table_id_src']).cumcount()+1

# Primary DX codes should be the most frequent position used in the raw tables, mapping positions based on how frequent they should be
diag_position_df.loc[diag_position_df['table_id_src'].isin(['ccaes', 'mdcrs']), 'diag_position'] = diag_position_df.loc[diag_position_df['table_id_src'].isin(['ccaes', 'mdcrs']), 'diag_position'].map({'P': 1, '1': 2, '2': 3, '3': 4, '4': 5})
diag_position_df['diag_position'] = diag_position_df['diag_position'].astype(int)

diag_position_df['position_check'] = diag_position_df['row_rank'] == diag_position_df['diag_position']
diag_position_df[~diag_position_df['position_check']]

Empty DataFrame
Columns: [data_source, year, table_id_src, diag_position, claim_count, row_rank, position_check]
Index: []

## ICD Version

In [34]:
query = '''drop table if exists qa_reporting.dw_truv_icd_version_count;
select data_source, year, icd_version, count(distinct uth_claim_id) as claim_count
into qa_reporting.dw_truv_icd_version_count
from dw_staging.trum_claim_diag
group by 1,2,3;

insert into qa_reporting.dw_truv_icd_version_count
select data_source, year, icd_version, count(distinct uth_claim_id) as claim_count
from dw_staging.truc_claim_diag
group by 1,2,3;
'''
with connection.cursor() as cursor:
    cursor.execute(query)

In [35]:
icd_version_df = pd.read_sql('select * from qa_reporting.dw_truv_icd_version_count;', con=connection)
icd_version_df.sort_values(['data_source', 'year', 'icd_version'])

C:\Users\iperez9\.conda\envs\psycog_env\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

   data_source  year icd_version  claim_count
69        truc  2011           0         1456
38        truc  2011           9         4184
42        truc  2011        None    486715834
9         truc  2012           0         1790
6         truc  2012           9         5283
..         ...   ...         ...          ...
0         trum  2021           9         1048
24        trum  2021        None         4645
26        trum  2022           0     42626513
31        trum  2022           9           33
65        trum  2022        None         3536

[72 rows x 4 columns]

In [36]:
icd_version_df[icd_version_df['data_source'] == 'truc'].sort_values(['year', 'icd_version'])

   data_source  year icd_version  claim_count
69        truc  2011           0         1456
38        truc  2011           9         4184
42        truc  2011        None    486715834
9         truc  2012           0         1790
6         truc  2012           9         5283
2         truc  2012        None    496302656
40        truc  2013           0         3442
57        truc  2013           9        10258
5         truc  2013        None    390003953
10        truc  2014           0         9867
56        truc  2014           9        30277
16        truc  2014        None    416414262
43        truc  2015           0     68255804
21        truc  2015           9    196856162
39        truc  2015        None        11370
63        truc  2016           0    273997108
4         truc  2016           9       176945
18        truc  2016        None        12602
64        truc  2017           0    254111052
14        truc  2017           9        53790
1         truc  2017        None         4682
70        truc  2018           0    260705407
25        truc  2018           9        32999
33        truc  2018        None         5109
23        truc  2019           0    251442583
54        truc  2019           9        33782
48        truc  2019        None         3706
15        truc  2020           0    225801941
41        truc  2020           9         9625
22        truc  2020        None         3239
11        truc  2021           0    248610913
30        truc  2021           9        28142
29        truc  2021        None         3493
61        truc  2022           0    224597328
28        truc  2022           9        25982
35        truc  2022        None         4474

In [37]:
icd_version_df[icd_version_df['data_source'] == 'trum'].sort_values(['year', 'icd_version'])

   data_source  year icd_version  claim_count
13        trum  2011           0          347
68        trum  2011           9          970
60        trum  2011        None    116980600
36        trum  2012           0          379
19        trum  2012           9         1107
59        trum  2012        None    109005110
8         trum  2013           0          836
3         trum  2013           9         2865
50        trum  2013        None     96481406
37        trum  2014           0         2957
55        trum  2014           9         9769
58        trum  2014        None     87213814
46        trum  2015           0     13840921
34        trum  2015           9     40916842
51        trum  2015        None         1439
49        trum  2016           0     53506018
62        trum  2016           9         3351
45        trum  2016        None         1926
12        trum  2017           0     37422178
44        trum  2017           9         1533
66        trum  2017        None          178
71        trum  2018           0     28358083
17        trum  2018           9          914
52        trum  2018        None          177
53        trum  2019           0     46569998
7         trum  2019           9         1264
20        trum  2019        None          747
27        trum  2020           0     44014396
47        trum  2020           9           41
32        trum  2020        None         5065
67        trum  2021           0     38126260
0         trum  2021           9         1048
24        trum  2021        None         4645
26        trum  2022           0     42626513
31        trum  2022           9           33
65        trum  2022        None         3536